name: Mindful Labs
favicon: null
layout_spectrum: 0.04682091670110822
typography_spectrum: 0.5048443484120071
title: Mindful Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8fa'
    - '#4fd2c2'
    - '#8c88ff'
    - '#ffb258'
    - '#97d8d2'
  brandStrength: 0.5
  lightness: 0.9216078671161085
  saturation: 0.07901198579929769
  rhythmicContrast: 0.10069205262698233
purpose: []
